config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized to Edit this Friend" if @friend.nil?
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, local: true) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name, class: "form-control", placeholder: "First Name"%>
    </br>
  </div>

  <div class="field form-group">
    <%= form.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
    </br>
  </div>

  <div class="field form-group">
    <%= form.text_field :email, class: "form-control", placeholder: "Email" %>
    </br>
  </div>

<div class="field form-group">
    <%= form.number_field :user_id, value: current_user.id, id: :friend_user_id %>
    </br>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-striped table-hover">
  <thead class = "table-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>User Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody >
    <% @friends.each do |friend| %>
      <%if friend.user == current_user%>
        <tr>
          <td><%= friend.first_name %></td>
          <td><%= friend.last_name %></td>
          <td><%= friend.email %></td>
          <td><%= friend.user_id %></td>
          <td><%= link_to 'Show', friend %></td>
          <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
          <td><%= button_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Friend', new_friend_path, class: "btn btn-secondary" %>

app/views/friends/new.html.erb
<div class="card">
  <h4 class="card-header">New Friend</h4>
  <div class="card-body">
    <%= render 'form', friend: @friend %>
  </div>
</div>
<%= link_to 'Back', friends_path %>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-6 h-100 p-5 text-bg-light border rounded-3">

<h1>
  <%= @friend.first_name %>  <%= @friend.last_name %>
</h1>


<p>
  <%= @friend.email %>
</p>

<%= link_to 'Edit', edit_friend_path(@friend), class: "btn btn-secondary" %> 
<%= link_to 'Back', friends_path, class: "btn btn-dark"%>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark ">
  <div class="container-fluid">
    <%= link_to 'Friend App',
        root_path, class: "navbar-brand" %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to "About Us",
            home_about_path, class:"nav-link"%>
        </li>
      

        <% if user_signed_in? %>%
        <li class="nav-item">
            <%= link_to "Friends",
            friends_path, class:"nav-link"%>
           </li>
         <li class="nav-item">
        <%= link_to "Add Friend",
            new_friend_path, class:"nav-link"%>
        </li>
           <li class="nav-item">
            <%= link_to "Edit Profile",
            edit_user_registration_path, class:"nav-link"%>
           </li>
          <li class="nav-item">
           <%= button_to "Sign Out",
            destroy_user_session_path, method: :delete, class:"btn btn-dark"%>
           </li>

        <% else %>
         <li class="nav-item">
        <%= link_to "Sign Up",
            new_user_registration_path, class:"nav-link"%>
        </li>
          <li class="nav-item">
          <%= link_to "Sign In",
              new_user_session_path, class:"nav-link"%>
          </li>

      <% end %>
    

      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Hello World</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <title>Friends App</title>
  </head>

  <body>
  <%= render 'home/header' %>
    <div class = "container">
      <br>
       <%= yield %>
    </div>
  </body>

</html>